
def build_preprocessor():
    ...

def fit_preprocessor(preprocessor, X_train):
    ...

def transform_data(preprocessor, X):
    ...

def save_preprocessor(preprocessor, path):
    ...

def load_preprocessor(path):
    ...